W&B disabled.
W&B online. Running your script from this directory will now sync to the cloud.
wandb: Currently logged in as: hl57. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.12 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.10
wandb: Run data is saved locally in /media/techt/One Touch/DD/SRe2L/train/wandb/run-20231022_005710-zg709bbd
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run ethereal-dust-442
wandb: ‚≠êÔ∏è View project at https://wandb.ai/hl57/final_rn18_fkd
wandb: üöÄ View run at https://wandb.ai/hl57/final_rn18_fkd/runs/zg709bbd
======= FKD: dataset info ======
path: ../relabel/FKD_cutmix_fp16/imagenette/251/
num img: 100
batch size: 100
max epoch: 300
================================
load data successfully
=> loading student model 'resnet18'
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run ethereal-dust-442 at: https://wandb.ai/hl57/final_rn18_fkd/runs/zg709bbd
wandb: Ô∏è‚ö° View job at https://wandb.ai/hl57/final_rn18_fkd/jobs/QXJ0aWZhY3RDb2xsZWN0aW9uOjk3MzkyNjU3/version_details/v43
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20231022_005710-zg709bbd/logs
Traceback (most recent call last):
  File "train_FKD.py", line 399, in <module>
    main()
  File "train_FKD.py", line 200, in main
    train(model, args, epoch)
  File "train_FKD.py", line 273, in train
    loss *= weights.to('cuda:0')
RuntimeError: The size of tensor a (25) must match the size of tensor b (100) at non-singleton dimension 0
